// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.8.1.0
//      SpecFlow Generator Version:1.8.0.0
//      Runtime Version:4.0.30319.239
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SpecsAgainstController.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.8.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Navigating the activity list")]
    public partial class NavigatingTheActivityListFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "NavigatingTheActivityList.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Navigating the activity list", "In order to keep track on what\'s happening in the company\r\nAs a user\r\nI want to s" +
                    "ee the current activities", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Activity id",
                        "When",
                        "Number of hours",
                        "Who",
                        "At Customer",
                        "Heading",
                        "Description"});
            table1.AddRow(new string[] {
                        "1",
                        "2011-02-17",
                        "2",
                        "Marcus",
                        "Progressive .NET",
                        "SpecFlow",
                        "En dragning kring SpecFlow"});
            table1.AddRow(new string[] {
                        "2",
                        "2011-01-17",
                        "4",
                        "Marcus",
                        "LF",
                        "Kanban",
                        "En dragning om Kanban"});
            table1.AddRow(new string[] {
                        "3",
                        "2011-02-17",
                        "2",
                        "Anders",
                        "Avega",
                        "BDD",
                        "Beskrev vad BDD är för säljarna"});
#line 7
 testRunner.Given("the following activities in the database", ((string)(null)), table1);
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Navigating the Activity list")]
        [NUnit.Framework.CategoryAttribute("spec")]
        [NUnit.Framework.CategoryAttribute("marcusoftnet")]
        public virtual void NavigatingTheActivityList()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Navigating the Activity list", new string[] {
                        "spec",
                        "marcusoftnet"});
#line 14
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 15
 testRunner.When("I go to the Activity list");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "When",
                        "NumberOfHours",
                        "Heading",
                        "Description"});
            table2.AddRow(new string[] {
                        "2011-02-17",
                        "2",
                        "SpecFlow",
                        "En dragning kring SpecFlow"});
            table2.AddRow(new string[] {
                        "2011-01-17",
                        "4",
                        "Kanban",
                        "En dragning om Kanban"});
            table2.AddRow(new string[] {
                        "2011-02-17",
                        "2",
                        "BDD",
                        "Beskrev vad BDD är för säljarna"});
#line 16
 testRunner.Then("I should see the following activites", ((string)(null)), table2);
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("When Marcus view the activity list he only sees his activites")]
        [NUnit.Framework.CategoryAttribute("spec")]
        [NUnit.Framework.CategoryAttribute("marcusoftnet")]
        public virtual void WhenMarcusViewTheActivityListHeOnlySeesHisActivites()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("When Marcus view the activity list he only sees his activites", new string[] {
                        "spec",
                        "marcusoftnet"});
#line 23
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 24
 testRunner.Given("I am logged in as Marcus");
#line 25
 testRunner.When("I go to the Activity list");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "When",
                        "NumberOfHours",
                        "Heading",
                        "Description"});
            table3.AddRow(new string[] {
                        "2011-02-17",
                        "2",
                        "SpecFlow",
                        "En dragning kring SpecFlow"});
            table3.AddRow(new string[] {
                        "2011-01-17",
                        "4",
                        "Kanban",
                        "En dragning om Kanban"});
#line 26
 testRunner.Then("I should see the following activites", ((string)(null)), table3);
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
